env:
    global:
        - DOCKER_VERSION=18.09.0
        - DOCKER_COMPOSE_VERSION=1.20.1
sudo: required
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
services:
  - docker

deploy:
  provider: script
  script: bash deploy.sh




